### ISSUE TITLE
setToolTip error MissingPluginException(No implementation found for method setToolTip on channel tray_manager)

### ISSUE THREAD

**Issue by j787701730** [leanflutter/tray_manager#2]
```
await TrayManager.instance.setToolTip("hello world");
```
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setToolTip on channel tray_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      TrayManager.setToolTip (package:tray_manager/src/tray_manager.dart:116:5)
<asynchronous suspension>
#2      _MyAppState.setTray (package:task_reminder_flutter/main.dart:48:5)
<asynchronous suspension>
```

```
Flutter (Channel beta, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.9.0-0.1.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (3 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1
```

**Comment by lijy91** [comment]
已修复，请更新到 0.1.3
